name: security-scan 

on:
  pull_request: 
  push:
    branches:
      - main

jobs:
  scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: gitleaks 
        run: |
          echo "scaning gitleaks"

